config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :posts
  resources :users, only: %i[edit update]
  resources :maps, only: %i[index map]
  namespace :api do
    resources :posts, only: :index, defaults: { format: "json" }
  end
  post "/map_request", to: "maps#map", as: "map_request"
  post "/save_viewport", to: "maps#save_viewport", as: "save_viewport"
  get "/set_viewport", to: "maps#set_viewport", as: "set_viewport"
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index; end

  def save_viewport
    @viewport = Viewport.find_or_initialize_by(user_id: current_user.id)
    @viewport.sw_lat = viewport_params[:sw_lat]
    @viewport.sw_lng = viewport_params[:sw_lng]
    @viewport.ne_lat = viewport_params[:ne_lat]
    @viewport.ne_lng = viewport_params[:ne_lng]
    @viewport.save!
  end

  def set_viewport
    @viewport = Viewport.find_by(id: current_user.id)
  end

  private

    def viewport_params
      params.permit(:sw_lat, :sw_lng, :ne_lat, :ne_lng)
    end

    def map_params
      params.require(:post).permit(:body, :image).merge(user_id: current_user.id)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_index.html.haml
= form_with url: map_request_path, method: :post, class: "search_form d-flex" do |f|
  = f.text_field :address, placeholder: "Type place", class: "search_box form-control", id: "address-input"
  = f.button 'Search', id: 'search-submit', class: "btn btn-outline-dark btn-sm"
.d-flex.mt-2.mb-2
  %button.set-my-view.btn.btn-sm.btn-success my view
  %button.save-this-view.btn.btn-sm.btn-success.ml-1 save this view
#map

%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=#{ENV['gcp_api_key']}&libraries=places&callback=initMap", "data-turbolinks-eval": "false"}

:javascript
  if (map !== undefined) {
    initMap();
  }