config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :posts
  resources :users, only: %i[edit update]
  resources :maps, only: %i[index map]
  namespace :api do
    resources :posts, only: :index, defaults: { format: "json" }
  end
  post "/map_request", to: "maps#map", as: "map_request"
  post "/save_viewport", to: "maps#save_viewport", as: "save_viewport"
  get "/set_viewport", to: "maps#set_viewport", as: "set_viewport"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :place
  has_many :likes
  has_many :images, dependent: :destroy

  validates :user_id, presence: true
  validates :place_id, presence: true
  validates :place_name, presence: true
  validates :title, length: { maximum: 40 }
  validates :body, length: { maximum: 1000 }

  scope :other_users,  -> (current_user_id) { where("user_id != ?", current_user_id) }
  scope :already_visited,  -> { where(already_visited: 1) }
  scope :not_visited,  -> { where(already_visited: 0) }
  scope :recently_posted, -> { order(created_at: :desc) }
  scope :recently_visited, -> { order(visit_date: :desc) }
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @my_recent_posts = current_user.posts.order(created_at: :asc).includes(:place, :images)
    @posts = Post.where("user_id != ? and already_visited = ?", current_user.id, 1).order(created_at: :desc).limit(21).includes(:place, :images, :user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @post = Post.new
    @posts = Post.other_users(current_user.id).already_visited.recently_posted.limit(21).includes(:place, :images)
    @my_recent_posts = current_user.posts.already_visited.recently_posted.includes(:place, :images, :user)
    @my_all_posts = current_user.posts.already_visited.recently_visited.includes(:place, :images, :user)
    @wannagos = current_user.posts.not_visited.recently_posted.includes(:place, :images, :user)
  end

  def show
    @post = Post.find(params[:id])
    render "show.js.erb"
  end

  def new
    @post = Post.new
    if params[:already_visited] == "false"
      render "new_wannago.js.erb"
    else
      render "new.js.erb"
    end
  end

  def edit
    render "edit.js.erb"
  end

  def create
    @place = Place.find_or_initialize_by(place_id: place_params[:place_id])
    @place.lat = place_params[:lat]
    @place.lng = place_params[:lng]
    @place.save!
    @post = @place.posts.new(post_params)
    @post.save!

    if params[:images]
      image_params[:image].each do |_num, image|
        @post.images.create(image: image, post_id: @post.id)
      end

    end

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post.update!(post_params)

    if image_remove_params != ""
      imageRemoveIds = image_remove_params.split(",").map(&:to_i)
      remove_images = Image.where(id: params[:imageRemoveIds])
      remove_images.each(&:destroy)
    end

    if params[:images]
      image_params[:image].each do |_num, image|
        @post.images.create(image: image, post_id: @post.id)
      end
    end
    render "update.js.erb"
  end

  def destroy
    @other_posts_judge = Post.where(place_id: @post.place_id).length
    @post.destroy if @post.user_id == current_user.id
    render "destroy.js.erb"
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      place_name = params.require(:place_name)
      params.require(:post).permit(:title, :visit_date, :body, :already_visited).merge(user_id: current_user.id, place_name: place_name)
      # params.permit(:title, :visit_date, :body).merge(user_id: current_user.id, place_name: place_name)
    end

    def place_params
      params.permit(:place_id, :lat, :lng)
    end

    def image_params
      # params.require(:images)
      params.require(:images).permit({ image: {} })
    end

    def image_remove_params
      params.permit(:imageRemoveIds)[:imageRemoveIds]
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
.modal-header
  %h5.modal-title{id: "newPostModalTitle"}
    投稿内容を入力してください
  %button.close{id: "newPostModalClose", "data-dismiss": "modal"} &times;
.modal-body
  = form_with model: @post, class:'newpost-form__form', id: "post-#{action_name}-form", local: true do |f|
    .form-group
      .field-label
        = f.label :title, "タイトル"
      .field-input
        = f.text_field :title, placeholder: "タイトル（40文字まで）", class: "form-control"
    .form-group
      .field-label
        = f.label :visit_date, "訪問日"
      .field-input
        - today = Date.today.strftime("%Y-%m-%d")
        = f.date_field :visit_date, class: "form-control", id: "newPostFormVisitDate", max: today
    .form-group
      %h6 写真
      #file-drop-area
        %p#newpost-modal__image-text.newpost-modal__image-text.text-center.text-muted
          ドラッグ&ドロップ
          %br
          またはクリックして画像をアップロード
        .dropzone-previews
          - if post.images != []
            - post.images.each do |image|
              .dz-preview.dz-image-preview
                .dz-image
                  = image_tag image.image_url, size: "120x120", class: "post-edit-image"
                %a.edit-image-remove.dz-remove{href: "#", "data-image-remove": "#{image.id}"} 削除
      -# = f.fields_for :images do |fin|
      -#   = fin.label :image, "写真" do
      -#     .item-registration__form__group__image{id: 'file-drop-area'}
      -#       .nest-form__head
      -#         = fin.file_field :image, multiple: true, name: 'images[image][]', style:"display:none;", class: "form-control newPostFormImages"
      -#         %p ドラッグアンドドロップ
      -#         %p またはクリックしてファイルをアップロード

    .form-group
      .field-label
        = f.label :body, "本文"
      .field-input
        = f.text_area :body, placeholder: "本文を入力（1000文字まで）", class: "form-control", id: "newPostFormBody"
    .modal-footer
      - if action_name == 'edit'
        = f.submit "保存", {id: "editPostFormSubmit", class: "btn btn-warning"}
      - else
        = f.submit "投稿", { id: 'newPostFormSubmit', class: "btn btn-warning", data: {disable_with: false}}

app/views/posts/_post.html.haml
.post.flip-box.card.mt-2.mt-lg-0.mb-1{"data-postid": "#{post.id}", "data-lat": "#{post.place.lat}", "data-lng": "#{post.place.lng}"}
  .flip-box-inner
    = image_tag post.images.first.image_url, class: 'flip-box-front card-img img-fluid' if post.images.first.present?
    .card-img-overlay
      = user_icon(post.user, {class: "post__user-icon mt-n2 ml-n2"})
      = post.user.name
      -# %h5.card-title.post__place-name
      -#   = post.place_name
      -# - if post.visit_date.present?
      -#   %h6.card-subtitle.text-muted.mb-1.post__date
      -#     visited_on: 
      -#     = post.visit_date
    .flip-box-back.card-body
      %h5.card-title.post__place-name
        = post.place_name
      - if post.visit_date.present?
        %h6.card-subtitle.text-muted.mb-1.post__date
          visited_on: 
          = post.visit_date

app/views/posts/_post_card.html.haml
.post-card.card.mx-3.mb-1{"data-postid": "#{post.id}", "data-lat": "#{post.place.lat}", "data-lng": "#{post.place.lng}"}
  = image_tag post.images.first.image_url, class: 'card-img-top img-fluid' if post.images.first.present?
  - if post.images.present?
    .card-img-overlay
      = user_icon(post.user, {class: "post-card__user-icon m-n2"})
      %span.ml-2
        = post.user.name
  .card-body
    %h4.card-title
      = post.place_name
    %p.card-text
      = post.title
    - if post.already_visited == false
      %p.card-text
        = post.body
    %p.card-text
      %small.text-muted
        - if post.visit_date.present?
          %h6.card-subtitle.text-muted.mb-1.post__date
            visited_on: 
            = post.visit_date

app/views/posts/_show_modal.html.haml
.modal-header
  %h5.modal-title{id: "postShowModalTitle"}
    = post.place_name
  %button.close{id: "postShowModalClose", "data-dismiss": "modal"} &times;
.modal-body
  %p
    = post.title
  %p
    = post.user.name
  %p
    = post.visit_date
  
  #postShowSlider.carousel.slide{"data-ride": "carousel"}
    - if post.images.length > 1
      %ol.carousel-indicators
        - post.images.each_with_index do |image, i|
          - if i == 0 
            %li.active{"data-target": "#postShowSlider", "data-slide-to": "0"}
          - else
            %li{"data-target": "#postShowSlider", "data-slide-to": "#{i}"}
    .carousel-inner.bg-dark
      - post.images.each_with_index do |image, i|
        - if i == 0
          .carousel-item.active
            = image_tag image.image_url, class: "slider__image"
        - else
          .carousel-item
            = image_tag image.image_url, class: "slider__image"
    - if post.images.length > 1
      %a.carousel-control-prev{href: "#postShowSlider", "data-slide": "prev"}
        %span.carousel-control-prev-icon
      %a.carousel-control-next{href: "#postShowSlider", "data-slide": "next"}
        %span.carousel-control-next-icon

  %p
    = post.body
  .modal-footer
    - if post.user_id === current_user.id
      = link_to post_path(post), method: :delete, remote: true, class:"" do
        .btn.btn-danger 削除
      = link_to edit_post_path(post),remote: true, class: "edit-link", data: {"turbolinks": false} do
        .btn.btn-warning 編集
    #postEditBtn.d-none{"data-toggle": "modal", "data-target": "#newPostModal"}

app/views/posts/_wannago_form.html.haml
.modal-header
  %h5.modal-title{id: "wannagoNewModalTitle"}
    投稿内容を入力してください
  %button.close{id: "wannagoNewModalClose", "data-dismiss": "modal"} &times;
.modal-body
  = form_with model: @post, class:'newpost-form__form', id: "post-#{action_name}-form", local: true do |f|
    .form-group
      .field-label
        = f.label :body, "メモ"
      .field-input
        = f.text_field :body, placeholder: "メモ（1000文字まで）", class: "form-control"
      = f.hidden_field :already_visited, {value: false}
    .modal-footer
      - if action_name == 'edit'
        = f.submit "保存", {id: "editPostFormSubmit", class: "btn btn-warning"}
      - else
        = f.submit "投稿", { id: 'newPostFormSubmit', class: "btn btn-warning", data: {disable_with: false}}

app/views/posts/destroy.js.erb
$('#postShowModalClose').trigger('click');
infowindow.close();
<% if @other_posts_judge == 1 %>
  clickedMarker.setMap(null);
<% end %>

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/edit.js.erb
(function() {
  $('#postShowModalClose').trigger('click');
  $('#postEditBtn').trigger('click');
  $('#newPostModalContent').empty();
  <% if @post.already_visited == true%>
    $('#newPostModalContent').append("<%= j(render partial: 'posts/form', locals: {post: @post}) %>");
    let placeName = clickPlace.name !== undefined ? clickPlace.name : clickPlace.place_name;
    $('#newPostModalTitle').text(placeName);
    let url = "/posts/<%= @post.id %>";
    let method =  'patch'
    initDropzone(url, method);
  <% else %>
    $('#newPostModalContent').append("<%= j(render partial: 'posts/wannago_form', locals: {post: @post}) %>");
    let placeName = clickPlace.name !== undefined ? clickPlace.name : clickPlace.place_name;
    $('#wannagoNewModalTitle').text(placeName);
  <% end %>
}());

app/views/posts/index.html.haml
#home.post-index-wrapper.w-100{"data-spy": "scroll", "data-target": "#main-nav"}

  %nav#main-nav.my-navbar.navbar.navbar-expand-sm.bg-dark.navbar-dark.fixed-top
    .container-fluid
      = link_to root_path, class:'navbar-brand d-flex', "data-turbolinks":"false" do
        = image_tag 'apple-touch-icon-180x180.png', alt: 'img', height: '50px', width: '50px', class: 'icon'
        %h1.my-navbar__head.ml-3 Footprints

      %button.navbar-toggler{"data-toggle": "collapse", "data-target": "navbarCollaplse"}
        %span.navbar-toggler-icon
      #navbarCollapse.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto
          %li.nav-item
            = link_to "My map", "#home", class: "nav-link"
          %li.nav-item
            = link_to "Wannagos", "#wannagos-head-section", class: "nav-link"
          %li.nav-item
            = link_to "Footprints", "#footprints-head-section", class: "nav-link"
          %li.nav-item
            = user_icon(current_user, {class: "my-navbar__avatar nav-link", "data-toggle": "modal", "data-target": "#userEditModal"})

  %main.main.container-fluid
    .row
      .latest-posts.bg-light.col-lg-2
        .latest-posts__head.d-flex.justify-content-center.align-items-center.border.mb-2.p-1.pr-4.bg-white
          = image_tag asset_path('someones_marker.png'), alt: 'img', height: '40rem', width: '40rem', class: 'icon'
          %h5.text-center.m-0 latest
          = fa_icon "chevron-circle-left", class: "latest-posts__chevron fa-2x ml-3"
        .latest-posts__content.d-flex.flex-lg-column
          = render @posts

      .map-wrapper.col-lg-8
        = render 'maps/index'

      .my-recent-posts.bg-light.col-lg-2
        .my-recent-posts__head.d-flex.justify-content-center.align-items-center.border.mb-2.p-1.pr-4.bg-white
          = image_tag asset_path('footprint_marker.png'), alt: 'img', height: '40rem', width: '40rem', class: 'icon'
          = fa_icon "chevron-circle-right", class: "my-recent-posts__chevron fa-2x ml-3"
          %h5.text-center.m-0 recent
        .my-recent-posts__content.d-flex.flex-lg-column
          = render partial: 'post', collection: @my_recent_posts

  %section#wannagos-head-section.user-wannagos-index
    .container-fluid
      .row.flex-column
        %h1.text-center.bg-light.user-wannagos-index__head
          = image_tag asset_path('wannago_marker.png'), alt: 'img', height: '40rem', width: '40rem', class: 'icon'
          Wannagos
        - if @wannagos.empty?
          %h3.text-center
            まだ行きたい場所はありません。
        .d-flex.justify-content-center
          - @wannagos.each do |wannago|
            = render partial: 'post_card', locals: {post: wannago}


  %section#footprints-head-section.user-posts-index.my-3
    .container-fluid
      .row.flex-column
        %h1.text-center.bg-light
          = image_tag asset_path('footprint_marker.png'), alt: 'img', height: '40rem', width: '40rem', class: 'icon'
          Footprints
        - year_month = []
        - count = 0
        - @my_all_posts.each do |post|
          - year_month_index = year_month.find_index {|x| x == post.visit_date&.strftime("%Y/%m")}
          - if year_month_index == nil
            %h2.user-posts-index__head.bg-light.text-center.mt-3.sticky-top
              = post.visit_date&.strftime("%Y/%m")
            - year_month << post.visit_date&.strftime("%Y/%m")
            %div.d-flex.w-100.justify-content-center
              - @my_all_posts.each do |post|
                - year_month_index = year_month.find_index {|x| x == post.visit_date&.strftime("%Y/%m")}
                - if year_month_index == count
                  = render partial: 'post_card', locals: {post: post}
              - count += 1

  %footer#main-footer.bg-dark
    .container
      .row
        .col.text-center.text-white.py-4
          %h3 Footprints
          %p
            Copyright &copy;
            %span#year
              = Date.today.strftime("%Y")
          %button.btn.btn-outline-warning{"data-toggle": "modal", "data-target": "#contactModal"}
            Contact Us

#newPostModal.modal.fade
  .modal-dialog
    #newPostModalContent.modal-content

#postShowModal.modal.fade
  .modal-dialog
    #postShowModalContent.modal-content

#userEditModal.modal.fade
  .modal-dialog
    #userEditModalContent.modal-content
      .modal-header
        %h5.modal-title アカウントの編集
        %button.close{"data-dismiss": "modal"} &times;
      .modal-body
        = form_for(current_user) do |f|
          .form-group
            .field-label
              = f.label :name
            .field-input
              = f.text_field :name, autofocus: true, class: "form-control"
          .form-group
            .field-label
              = f.label :email
            .field-input
              = f.email_field :email, class: "form-control"
          .form-group
            .field-label
              = f.label :avatar
            .field-input
              = f.file_field :avatar, class: "form-control"
          .modal-footer
            = f.submit "Update", class: 'btn btn-info'
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-outline-info'

app/views/posts/new.js.erb
(function() {
  $('#newPostModalContent').empty();
  $('#newPostModalContent').append("<%= j(render partial: 'posts/form', locals: {post: @post}) %>");
  let placeName = clickPlace.name !== undefined ? clickPlace.name : clickPlace.place_name;
  $('#newPostModalTitle').text(placeName);
  let url = "/posts";
    let method =  'post'
  initDropzone(url, method);
}());

app/views/posts/new_wannago.js.erb
(function() {
  $('#newPostModalContent').empty();
  $('#newPostModalContent').append("<%= j(render partial: 'posts/wannago_form', locals: {post: @post}) %>");
  let placeName = clickPlace.name !== undefined ? clickPlace.name : clickPlace.place_name;
  $('#wannagoNewModalTitle').text(placeName);
}());

app/views/posts/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/posts/show.js.erb
$('#postShowModalContent').append("<%= j(render partial: 'posts/show_modal', locals: {post: @post}) %>");